name: Sync F2FS from A15
on:
  workflow_dispatch:

# --- YE BLOCK ADD KARO ---
permissions:
  contents: write
# -------------------------

jobs:
  copy-f2fs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout A31 Repo (Target)
        uses: actions/checkout@v4
        with:
          path: a31_repo

      - name: Checkout A15 Repo (Source)
        uses: actions/checkout@v4
        with:
          repository: oppo-source/A15
          path: a15_repo

      - name: Copy F2FS Folder
        run: |
          mkdir -p a31_repo/kernel-4.9/fs/
          cp -rv a15_repo/kernel-4.9/fs/f2fs a31_repo/kernel-4.9/fs/
          
      - name: Commit and Push changes
        run: |
          cd a31_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add kernel-4.9/fs/f2fs
          git commit -m "Add F2FS filesystem drivers from Oppo A15" || exit 0
          git push
